Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network", bridge: 1, ip: "192.168.0.5"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.name = "vagrant-shell-script"
  end

  # Timeout para primeira inicialização
  config.vm.boot_timeout = 1000 

  # Fazendo a chamado no arquivo de shell
  config.vm.provision "shell", path: "config-server-ubuntu.sh"
  
end
