Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network", ip: "192.168.0.3"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    vb.name = "vagrant-zabbix-server"
  end

  config.vm.boot_timeout = 1000 
  config.vm.provision "file", source: "comando01.sql", destination: "/home/vagrant/comando01.sql"
  config.vm.provision "file", source: "comando02.sql", destination: "/home/vagrant/comando02.sql"
  config.vm.provision "shell", path: "config-server-ubuntu.sh"
  config.vm.provision "shell", path: "./Projects/autorize_user_ssh.sh"
end
