Vagrant.configure("2") do |config|
  # Imagem do Vagrant HUB
  config.vm.box = "ubuntu/focal64"

  # Informar o IP da máquina na sua faixa de IP
  config.vm.network "public_network", ip: "192.168.0.117"

  # Se preferir pode utilizar uma configuração com dhcp e private_network
  # config.vm.network "public_network", type: "dhcp"
  # config.vm.network "private_network", type: "dhcp"


  # Se utiliza o VMware pode utilizar essa configuração para o provider
  # config.vm.provider "vmware_desktop" do |vmware|

  # Virtualizador virtualbox
  config.vm.provider "virtualbox" do |vb|
    # 8GB de memória
    vb.memory = "8192"
    # Quantidade núcleos
    vb.cpus = "4"
    # Nome da máquina
    vb.name = "Ubuntu-Server"
  end

  # Timeout para primeira inicialização
  config.vm.boot_timeout = 1000 

  # Scripts de execução para configuração do ambiente
  config.vm.provision "shell", path: "config-server-ubuntu.sh"
  config.vm.provision "shell", path: "./Projects/autorize_user_ssh.sh"
  
end
