Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network", bridge: 1, ip: "192.168.0.4"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.name = "vagrant-ubuntu"
  end

  # Timeout para primeira inicialização
  config.vm.boot_timeout = 1000 

  # Sincronizando o folder tmp local
  config.vm.synced_folder "./tmp", "/tmp"

  # Scripts
  config.vm.provision "shell", path: "./Projects/autorize_user_ssh.sh"

end
