Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest:80, host: 8090
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.name = "vagrant-shell-script-nginx"
  end

  config.vm.provision "file", source: "./html", destination: "/tmp"

  # Timeout para primeira inicialização
  config.vm.boot_timeout = 1000 

  # Scripts de execução para configuração do ambiente
  config.vm.provision "shell", path: "config-server-ubuntu.sh"
  
end
